name: jstest

on:
  push:
  pull_request:

jobs:
  jstest:

    name: jstest-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup npm
      uses: actions/setup-node@v3

    - name: Install npm dependencies
      run: npm ci
    
    - name: Run jest tests
      run: npm test
